### ISSUE TITLE
maintained project?

### ISSUE THREAD

**Issue by alexnaspo** [groupon/schema-inferer#1]
Hi all,

I'm an engineer at jet.com and we are attempting to solve the exact same problem. We are potentially interested in using this tool. I see there haven't been any commits in ~6 months. Is this actively worked on? Are you using this in production? 

Best,

Alex

**Comment by JessicaLHartog** [comment]
Hi @alexnaspo 
There haven't been any commits in the last 6 months because we have not encountered a need for new functionality, nor have we encountered any bugs. We are running this code in production at Groupon. Right now the next slated updates to this repo (pending no bug discoveries or feature requests) are to iterate on the versions of Spark/Kafka as we perform upgrades.

**Comment by alexnaspo** [comment]
That's great news. Thank you for the information! @JessicaLHartog
